apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: benchmark
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      serviceAccountName: aaron-benchmark-sa
      terminationGracePeriodSeconds: 1
      containers:
        - image: google/cloud-sdk:latest
          imagePullPolicy: IfNotPresent
          name: gcloud
          env:
            - name: BUCKET
              value: cohere-gcp-benchmark
            - name: MODEL_PATH
              value: small-model
          command:
            - /bin/bash
            - -c
            - |
              apt-get update && apt-get install -y net-tools
              name=$(curl -s http://metadata.google.internal/computeMetadata/v1/instance/name -H "Metadata-Flavor: Google")
              time gcloud storage cp -r gs://$BUCKET/$MODEL_PATH/ /mnt/models/fastertransformer/
              sleep infinity
          volumeMounts:
            - mountPath: /mnt/models/fastertransformer
              name: model
          resources:
            requests:
              memory: 100G
              cpu: "30"
      volumes:
        - name: model
          emptyDir:
            medium: Memory
